!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --partition=gpu
#SBATCH --time=03:00:00
#SBATCH --output=bert_frozen_%A.out
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=r.s.oort@gmail.com

module purge
module load 2022
module load Anaconda3/2022.05

source activate dl2021

wandb login

python3 main.py --model bert-base-uncased --epochs 25 --batch_size 8 --save_dir Finetuned/bert/frozen --freeze --wandb
