wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
model:
  desc: null
  value: bert
epochs:
  desc: null
  value: 1
freeze:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696103535.30554
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.9.7
      5: 0.14.2
      6: 4.28.1
      8:
      - 5
